sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t cashmyers/usaag-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true cashmyers/usaag-frontend npm run test



