sudo: required

language: node.js
node_js:
  - 16

services:
  - docker

before_install:
  - docker build -t cashmyers/usaag-frontend -f Dockerfile .

script:
  - docker run -e CI=true cashmyers/usaag-frontend npm run test



