# Specify the version
version: '3.9'

#Declare the service
services:

  # Define the service
  usaag-frontend-prod:
    container_name: usaag-frontend-prod

    # Define the build context
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/usr/app
      - ./node_modules:/usr/src/app/node_modules

    # Map the ports
    ports:
      - '1561:80'
