# Specifiy the version
version: '3.9'

#Declare the service
services:

  # Define the service
  usaag-frontend-prod:
    container_name: usaag-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod

    # Map the ports
    ports:
      - '1561:80'
