# pull official base image
FROM node:lts-alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install

# Add modified webconfig file to dependency conflic
COPY ./.saved_src/webpack.config.js ./node_modules/react-scripts/config/webpack.config.js

# add app
COPY . ./

# start app
CMD ["npm", "start"]